[RSpec編] 04_未完成のテストコード修正
yukimura907/rspec_app_exam pull request #1
Opened 2020-12-12 15:27 UTC by yukimura907

FIXME,TODOを全て達成し、全てのテストコードがパスしたのでご確認お願いいたします。
NG集も確認したので正しいコードになっているはずです。
今回も実装に夢中で途中のcommitを忘れてしまっていたので、一気にcommitしてしまいました。。。

１つだけどうしても腑に落ちない点があり、
`it 'Taskが削除されること' do`のテストで
`expect(Task.count).to eq 0`だと`expected '0'   got '1'`とエラーが出てどうしても通りませんでした。
debuggerを挟んでTask.countの値を確認したらしっかりと'0'になっており、なぜテストが通らなかったのかどうしてもわかりません。
`find('tbody')`と追記するとなぜか通りましたので、HTMLの文字列がカウントされているのかと思いTasks of ○○の部分をtasks of ○○とかに変えてみてもダメでした。

<img width="1440" alt="スクリーンショット 2020-12-12 23 56 58" src="https://user-images.githubusercontent.com/70642468/101987352-ea822e00-3cd6-11eb-998b-81491aba0735.png">
<img width="1440" alt="スクリーンショット 2020-12-12 23 57 08" src="https://user-images.githubusercontent.com/70642468/101987358-f53cc300-3cd6-11eb-8c95-6fd3a802ff95.png">

2020-12-13 05:25 UTC, yuji91 commented
> 今回も実装に夢中で途中のcommitを忘れてしまっていたので、一気にcommitしてしまいました。。。

基本レビュー依頼する際はコミット細か過ぎなくても良いので（現場にもよりますが）
指摘事項もらったら細かく対応すれば良いかと思います！

2020-12-13 05:46 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect('tbody').not_to have_content task.title
Rubyの仕様で1行の処理が完全に終了してから次の行が実行されるのではなく、前の行の処理が実行中でも次の行の処理が開始されることがあります。（インタプリタ形式でコードを読み込んで順に実行するのが原因と思われます。）

そのため、高速で処理が終わってしまう記法だと、前の行の処理が重い場合はその結果を反映出来ないことがあります。
今回はデータベースの変更を伴う処理があるので、Task.countの記載の直前に`sleep 1`など待機するように指示するとテストが通ります。

changeと記載することでテストが通ったのは、changeという変更結果の前後を検証するというTask.countより時間のかかる記載になったため、前の行の処理が終わってから実行結果が出るのでテストが成功したかと思います。

Task.countの記載でsleepを使わないで記載する場合は`expect('tbody').not_to have_content task.title`の画面上の情報を取得する処理を少し時間がかかるように`find`を使って記載するとテストが通るかと思います。

2020-12-13 05:47 UTC, yuji91 commented on spec/factories/tasks.rb
> +    end
associationを定義すると`let(:task)`でproject_idを指定する必要が無くなります。

2020-12-13 05:48 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.last)
好みもありますが、一応この処理は1行で記載可能です。

2020-12-13 05:48 UTC, yuji91 requested changes
細かい点をコメントしました！

2020-12-13 06:21 UTC, yukimura907 commented
なるほど！！！！
めちゃめちゃ納得しました！！！
projectの削除テストの方で通っていたのは、アラートメッセージのテストコードや複数のnot_to have_contentのコードを間に挟んでいたから、その分処理が遅れていたんですね！

他の指摘点も修正してマージしておきますー！
ありがとうございました！！

2020-12-14 08:03 UTC, yuji91 commented
もしこのPR上で修正のコミットを行う場合は、指摘事項毎にコミットを分けておくと良いと思います！

2020-12-15 02:40 UTC, merged